# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: javademo
services:
  app:
    image: javademo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9083/management/health']
      interval: 5s
      timeout: 5s
      retries: 40
